### PR TITLE
Changed form-submission-handler.js file into IIFE

### PR DESCRIPTION
**Pull request by Confidenceiskey**
Deleted lines 104, 109 & 110 in original. Indented the entire file & wrapped it into an IIFE. 

Not sure why it shows that everything was modified though?

### CODE REVIEW

**Comment by mckennapsean** [comment]
@Confidenceiskey it shows all the modifications due to whitespace changes. You can change the settings on the diff to ignore that and it's much simpler :)

Thanks for opening this separately!

Looks like this removes using `DOMContentLoaded` - not sure what the side effects may be, apart from it maybe not working if the DOM is large and not fully processed when the JS is called. I'll have to dig into that.

https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

**Comment by Confidenceiskey** [comment]
Oh sweet! That is awesome @mckennapsean! Yes that does make it so much simpler. Thanks for that.

I'm not sure on that either. My assumption/thought was that `DOMContentLoaded` wouldn't be necessary since the function doesn't do anything until the user clicks on the submit button anyways.

**Comment by mckennapsean** [comment]
@Confidenceiskey apologies on the delay - the delay there ensures that all form elements get the function. this is necessary in the case of large pages, or in case your HTML is changed by other Javascript. or if you inline the Javascript in head, it may try to run before the DOM is setup, which basically means the form won't work as intended anymore. so I think we need to keep it. it is the equivalent of JQuery's window/load paradigm.

**Comment by mckennapsean** [comment]
thanks for opening this! to avoid the issue mentioned above, I opened a new PR if you wanted to take a look: #235 

Tested and works well :+1: thank you very much for your contribution!

**Pull request closed without merging**
