### PR TITLE
Actually log errors

### PR DESCRIPTION
**Pull request by lesander**
Hi there!

I stumbled across a small typo in `google-apps-script.js` while debugging the project. Errors caught by the try/catch blocks are not always shown as expected. This file change should fix that.

Cheers 🍻

### CODE REVIEW

**Comment by mckennapsean** [comment]
Thanks for taking a look & catching some of that!

I do agree we should log the errors better.

Currently, it is logging the variable `e` which in both cases is the object/json/blob being passed to each of the functions. That information may still be useful (and in the case of failures, it means you can get the values that someone submitted still).

On that note, have you had any experience with Google Script's Logger? I have not ever tried to get it working, but I never found a simple way to surface and check for these errors to validate that they are (or are not) working as intended.

**Comment by lesander** [comment]
Hi Sean, thanks for the quick reply. 

I agree that the request variable `e` is indeed also useful when debugging. Perhaps logging both the error and the request objects would be a better solution.

Regarding Google's Logger Class, I've actually learned form the GAS Documentation that [using `console.log` is preferred now](https://developers.google.com/apps-script/guides/logging). It turns out that logs made with the Logger class are only logged when the GA Script is called manually in the Script Editor, while `console[..]` calls are always logged in the Stackdriver over at Google's Cloud Platform site (Can be accessed in the Script Editor through "View -> Stackdriver Logging").

While playing with the GAS script last night, I've actually made a few more improvements as well. I'll share them with you ASAP.

**Comment by mckennapsean** [comment]
Very cool! Feel free to open other PRs. Yes, I agree that showing both would be ideal.

It definitely sounds like we should use Stackdriver by default. There are some additional gotchas (extra terms of service, a cloud feature that may not be open to all users), but the benefits of long-term logging are more useful. I had never actually dug into the documentation on the built-in Logger, so that is good to know how to make that work too. Thanks for the link!

**Comment by lesander** [comment]
Hi there. It's been a while 😄. I'm running a modification of this script on a client's (open-source) website now. It has recaptcha support, uses the Stackdriver Logging method and has an improved JSON API response structure. I've also added some more comments and documentation. 

Would you like some features of this modification in a PR?

https://github.com/ieni/website/blob/master/_gs/sendmail.gs

**Comment by mckennapsean** [comment]
I am open to the idea, but I would have to look further. Seems like you have some refactors / code cleanup which is welcome, I think.

Advanced features, like recaptcha, may make the initial tutorial more complex, but it would be a great example to include in the "advanced" section at the end of the tutorial. Perhaps the simplest is to include your working example as a link, if you/your client are okay with that (or fork your work into an open source repo and link that instead perhaps).

I assume we are welcome to other changes, but I am not sure how to best advise that, not sure if @nelsonic  or @iteles have any thoughts there.

**Comment by mckennapsean** [comment]
Thanks for the contribution & awesome fix here, @lesander!

If you would like to open further PRs on any future improvements, let us know! I saw that the Logger code was working when you have it open, which may be good enough for most folks. Wanting to get this in since it is a significant improvement. Thanks again!

**Pull request merged**
