### PR TITLE
Support for array / multi-input

### PR DESCRIPTION
**Pull request by goatandsheep**

### CODE REVIEW

**Comment by mckennapsean** [comment]
Thanks for the PR @goatandsheep ! 

I have been amassing a collection of form use-cases (in `test.html`), and I didn't see any difference using your code, since everything is just a single value. Even in the case of multiple items for a single form field, it is already turning that array into a string of values.

Are you doing something else with your form? I am just curious of the use-case. We have similar code doing this client-side, in `form-submission-handler.js`, so it may make more sense there.

If you have an example / demo where the issue is occurring, that could be useful to see.

Thanks!

**Comment by goatandsheep** [comment]
For [multi-select form inputs](https://www.w3schools.com/tags/att_select_multiple.asp), it is represented with an array.

**Comment by mckennapsean** [comment]
Thanks for sharing that link! We will want to pull in an example field in `test.html` to incorporate this bug as well. Feel free to do so, otherwise I can take add it at some point (and see if any other types are missing). May be worth adding an issue on this missing form type.

**Comment by mckennapsean** [comment]
Sweet, I finally figured out what you meant, sorry it took so long @goatandsheep !

It was working just fine if you have the JS clientside code, since we would do that cleanup there. Now I have figured out all the "error: error" issues people have had, and I can clean up the main repo to handle this and stop as many of the errors if people forget the clientside code. They just won't get proper order of data without it. Thanks @goatandsheep !

**Comment by mckennapsean** [comment]
Thank you very much for your contribution, @goatandsheep !

I incorporated your work into a new PR that fixes another bug, since we broke form submission if you weren't using our custom code to do the generation of the POST request from the form data. Now with this fix, I am seeing consistent spreadsheet output of a form's data with and without our clientside JS. Feel free to take a look & code review. #237

**Pull request closed without merging**
