### PR TITLE
FIX Multiple form submissions

### PR DESCRIPTION
**Pull request by rdhar**
Newer standard of handling multiple form submissions using ["once" event listener](https://caniuse.com/#feat=once-event-listener) instead of resorting to disabling the submit button or more hacky solutions. Addresses #202 .

N.B. A few whitespace changes have crept in automatically from my text editor which adjusts spacing after a couple of multiline comments. Feel free to ignore/reject them, as you wish.

### CODE REVIEW

**Comment by mckennapsean** [comment]
thanks for the neat PR fix, @rdhar !

I had not known about `once` parameter to the listener, very awesome.

I will need to test this with our current validation method, since if the first submit fails, then the button may not work after that.

Also, it appears that `once` is not supported in IE. :(
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

@nelsonic & @iteles - do you know if that is a dealbreaker to not support IE?

**Comment by rdhar** [comment]
Fair point. I carried out "positive testing" to verify that I could no longer replicate the stated issue by clicking on the Submit button multiple times in quick succession while the form data was being posted. However, I wasn't aware "negative testing" was possible whereby a failure from prior form validation would affect the outcome of the submission in the first place. Do let me know if there's any way I can help test it out.

As far as browser compatibility is concerned, both the "once" even listener ([mozilla](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility)/[caniuse](https://www.caniuse.com/#feat=once-event-listener)) and Fetch API ([mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility)/[caniuse](https://www.caniuse.com/#feat=fetch)) are unsupported on any version of IE. As are many, _many_ other things.

It would be a shame to miss out on these benefits for the sake supporting a browser that Microsoft themselves are stepping away from (notice, fully compatible with both features on Edge!). Although, I can understand not wanting to break any existing reliance on backwards compatibility. In that case, this PR may be better suited as a separate demo page for non-IE browsers. I'll leave that up to you to handle as you see best fit 😄.

**Comment by iteles** [comment]
@mckennapsean @rdhar I really like the idea of having this as a separate demo, rather than merged into `master` (sadly, lack of compatibility with IE is still a big problem for lots of people!). @mckennapsean Any preference on how to get this done?

**Comment by mckennapsean** [comment]
hmmmm. I think I have asked the IE question before. IE 11 is going to be supported forever, and for some corporate customers, it is all they have access to if they cannot install on their system. but, someone can take what we have and make it to work with whatever browsers in their use case.

an example of code we could clean up is the ajax to use fetch, but would "lose" IE support (if it works right now...) https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server/issues/131

the changes here are rather small. it might be worth adding in the demo to the PR again, as I would like a way to test that this change does in fact work. I could probably dig through commits to find the example. I mostly have been swamped and unable to do development on this project... hopefully soon.

**Comment by mckennapsean** [comment]
After further review, I don't think we should regress to not support IE11. Enough people still use it, and it will be a hard requirement for people wanting to solve basic use-cases, like having forms work for a variety of clients.

As unfortunate as that is, it is a part of basic accessibility so that a variety of browsers and users get optimum behavior. Windows 10 supports IE 11, and some major enterprise clients may be stuck with their OS and browser with no control - we shouldn't make the form not work for them.

While we can get polyfills to work in older browsers, this complicates the tutorial which is already complex enough as-is. I think we could add advanced examples with future-support features, or some that don't limit us to IE support (which would streamline a lot) - but I think we need to keep the basics in mind for most people looking to benefit from this tutorial.

**Comment by mckennapsean** [comment]
I also realized another issue when working on a general fix here - the "once" attribute will enforce that we only run this action once, but there can be an unknown amount of these actions since we perform validation during the action. As a result, we need to more carefully keep the listener from firing more than once.

I implemented a solution in another PR #236 - thank you very much for your contribution @rdhar and getting us to implement the right fix here! feel free to take a look and provide any feedback or code review there. :)

**Pull request closed without merging**
